const COPY = {
  EN: {
    'Visão geral': 'Overview', Usuários: 'Users', Peças: 'Parts', Pedidos: 'Orders', Avaliações: 'Reviews', 'Validação de peças': 'Part validation',
    'Analise anúncios pendentes antes de disponibilizá-los no catálogo.': 'Review pending listings before making them available in the catalog.',
    'Configurar checklist': 'Configure checklist', Revisão: 'Revision', Mídia: 'Media', Imagem: 'Image', Vídeo: 'Video', 'Sem mídia': 'No media', 'Sem código': 'No code', 'Analisar anúncio': 'Review listing', Pendente: 'Pending',
    'Painel administrativo': 'Admin panel', 'Novo administrador': 'New administrator',
    'Acompanhe os principais números e a atividade da plataforma.': 'Track the platform’s main figures and activity.',
    'Gerencie acessos, perfis e permissões administrativas.': 'Manage access, profiles and administrative permissions.',
    'Consulte e modere os anúncios publicados no catálogo.': 'Review and moderate catalog listings.',
    'Acompanhe pedidos e atualize o andamento das transações.': 'Track orders and update transaction progress.',
    'Modere as avaliações enviadas pela comunidade.': 'Moderate reviews submitted by the community.',
    'Visão gerencial': 'Management view', 'Filtrar dashboard': 'Filter dashboard', 'O recorte abaixo atualiza indicadores e gráficos.': 'The selection below updates metrics and charts.',
    Período: 'Period', Status: 'Status', Fornecedor: 'Supplier', Limpar: 'Clear', 'Últimos 7 dias': 'Last 7 days', 'Últimos 30 dias': 'Last 30 days', 'Últimos 90 dias': 'Last 90 days', 'Último ano': 'Last year', 'Todo o período': 'All time', 'Todos os status': 'All statuses', 'Todos os fornecedores': 'All suppliers',
    'OPERAÇÃO ATUALIZADA': 'OPERATION UPDATED', 'Veja a saúde da operação e o que precisa da sua atenção.': 'See operation health and what needs your attention.', 'Administrador · Sessão protegida': 'Administrator · Protected session',
    Faturamento: 'Revenue', 'Ticket médio': 'Average order value', 'Taxa de conclusão': 'Completion rate', 'Taxa de cancelamento': 'Cancellation rate', Administradores: 'Administrators', Pendentes: 'Pending',
    'Evolução do faturamento': 'Revenue evolution', 'Receita, volume de pedidos e ticket médio.': 'Revenue, order volume and average order value.', Diário: 'Daily', Semanal: 'Weekly', Mensal: 'Monthly', Receita: 'Revenue',
    'Requer atenção': 'Needs attention', 'Itens que podem exigir uma ação agora.': 'Items that may require action now.', 'pedidos aguardando pagamento': 'orders awaiting payment', 'pedidos pagos aguardando envio': 'paid orders awaiting shipment', 'pedidos cancelados no período': 'orders canceled in the period',
    'Fluxo de pedidos': 'Order flow', 'Distribuição dos pedidos no recorte atual.': 'Order distribution in the current selection.', Plataforma: 'Platform', 'Dimensão atual da base.': 'Current platform size.', Admins: 'Admins',
    'Atividade recente': 'Recent activity', 'Movimentações mais relevantes da plataforma.': 'Most relevant platform activity.', 'Novo usuário cadastrado': 'New user registered',
    'Organizar dashboard': 'Organize dashboard', 'EDIÇÃO AO VIVO': 'LIVE EDITING', 'Organize seu dashboard': 'Organize your dashboard', 'Arraste os cards pela alça para mudar a ordem.': 'Drag cards by the handle to change their order.', 'Salvar layout': 'Save layout', 'Widgets ocultos': 'Hidden widgets', 'Ocultar widget': 'Hide widget',
    registros: 'records', 'Sem nome': 'Unnamed', 'Carregando registros…': 'Loading records…', 'Nenhum registro encontrado.': 'No records found.', 'vs. período anterior': 'vs. previous period', 'Sem base comparável no período anterior': 'No comparable baseline in the previous period', 'No período selecionado': 'In the selected period', 'Aguardando ação': 'Awaiting action', 'Total registrado': 'Total registered',
    Buscar: 'Search', 'Todos os registros': 'All records', Usuário: 'User', Perfil: 'Profile', Cadastro: 'Registered', Permissão: 'Permission', Ações: 'Actions', 'Tornar admin': 'Make admin', 'Editar usuário': 'Edit user', 'Excluir usuário': 'Delete user', Peça: 'Part', Estoque: 'Stock', 'Editar peça': 'Edit part', 'Excluir peça': 'Delete part', Cliente: 'Customer', Valor: 'Amount', Produtos: 'Products', Fornecedores: 'Suppliers', Nota: 'Rating', Comentário: 'Comment', Data: 'Date', Pedido: 'Order', 'Loja fornecedora': 'Supplier store', 'Peça avaliada': 'Reviewed part',
    'Novo administrador': 'New administrator', 'Gerenciamento de acesso': 'Access management', 'Crie uma conta verificada com acesso imediato ao painel.': 'Create a verified account with immediate panel access.', 'Nome completo': 'Full name', Senha: 'Password', 'Senha temporária': 'Temporary password', 'Criar administrador': 'Create administrator', Cancelar: 'Cancel', 'Salvar alterações': 'Save changes', 'Edição administrativa': 'Administrative editing', Telefone: 'Phone', 'Nome da loja': 'Store name', Preço: 'Price', 'Remover avaliação?': 'Remove review?', 'Esta ação não poderá ser desfeita.': 'This action cannot be undone.', 'Sim, excluir': 'Yes, delete',
    Editar: 'Edit', usuário: 'user', peça: 'part', avaliação: 'review', 'Revise os dados antes de salvar a alteração.': 'Review the information before saving.', 'O e-mail de acesso também será atualizado.': 'The sign-in email will also be updated.', 'Nome da peça': 'Part name', estrela: 'star', estrelas: 'stars', 'Mínimo de 8 caracteres, contendo letras e números.': 'At least 8 characters, including letters and numbers.', 'Criando…': 'Creating…', 'Sem comentário': 'No comment',
    'Total de contas ativas cadastradas na plataforma.': 'Total active accounts registered on the platform.', 'Contas que possuem acesso ao painel administrativo.': 'Accounts with access to the admin panel.', 'Total de anúncios de peças disponíveis no catálogo.': 'Total part listings available in the catalog.', 'Quantidade total de pedidos registrados na plataforma.': 'Total orders registered on the platform.', 'Pedidos que ainda aguardam pagamento ou ação operacional.': 'Orders still awaiting payment or operational action.', 'Avaliações publicadas por compradores.': 'Reviews published by buyers.', 'Soma dos pedidos não cancelados no período e filtros selecionados.': 'Sum of non-canceled orders for the selected period and filters.', 'Valor médio dos pedidos não cancelados no recorte atual.': 'Average value of non-canceled orders in the current selection.', 'Percentual de pedidos do período que foram entregues.': 'Percentage of orders delivered in the period.', 'Percentual de pedidos do período que foram cancelados.': 'Percentage of orders canceled in the period.',
  },
  FR: {
    'Visão geral': 'Vue d’ensemble', Usuários: 'Utilisateurs', Peças: 'Pièces', Pedidos: 'Commandes', Avaliações: 'Avis', 'Validação de peças': 'Validation des pièces', 'Painel administrativo': 'Panneau d’administration', 'Novo administrador': 'Nouvel administrateur',
    'Analise anúncios pendentes antes de disponibilizá-los no catálogo.': 'Examinez les annonces en attente avant de les publier dans le catalogue.',
    'Configurar checklist': 'Configurer la checklist', Revisão: 'Révision', Mídia: 'Média', Imagem: 'Image', Vídeo: 'Vidéo', 'Sem mídia': 'Sans média', 'Sem código': 'Sans code', 'Analisar anúncio': 'Examiner l’annonce', Pendente: 'En attente',
    'OPERAÇÃO ATUALIZADA': 'OPÉRATION À JOUR', 'Veja a saúde da operação e o que precisa da sua atenção.': 'Consultez la santé de l’activité et les éléments qui nécessitent votre attention.', 'Administrador · Sessão protegida': 'Administrateur · Session protégée', registros: 'enregistrements', 'Sem nome': 'Sans nom', 'Carregando registros…': 'Chargement des enregistrements…', 'Nenhum registro encontrado.': 'Aucun enregistrement trouvé.', 'vs. período anterior': 'par rapport à la période précédente', 'Sem base comparável no período anterior': 'Aucune base comparable sur la période précédente', 'No período selecionado': 'Sur la période sélectionnée', 'Aguardando ação': 'En attente d’action', 'Total registrado': 'Total enregistré', Administrador: 'Administrateur', 'Editar usuário': 'Modifier l’utilisateur', 'Excluir usuário': 'Supprimer l’utilisateur', 'Editar peça': 'Modifier la pièce', 'Excluir peça': 'Supprimer la pièce',
    'Visão gerencial': 'Vue de gestion', 'Filtrar dashboard': 'Filtrer le tableau de bord', 'O recorte abaixo atualiza indicadores e gráficos.': 'La sélection met à jour les indicateurs et graphiques.', Período: 'Période', Status: 'Statut', Fornecedor: 'Fournisseur', Limpar: 'Effacer', 'Últimos 7 dias': '7 derniers jours', 'Últimos 30 dias': '30 derniers jours', 'Últimos 90 dias': '90 derniers jours', 'Último ano': 'Dernière année', 'Todo o período': 'Toute la période', 'Todos os status': 'Tous les statuts', 'Todos os fornecedores': 'Tous les fournisseurs',
    Faturamento: 'Chiffre d’affaires', 'Ticket médio': 'Panier moyen', 'Taxa de conclusão': 'Taux d’achèvement', 'Taxa de cancelamento': 'Taux d’annulation', Administradores: 'Administrateurs', Pendentes: 'En attente', 'Requer atenção': 'À surveiller', 'Itens que podem exigir uma ação agora.': 'Éléments pouvant nécessiter une action.', 'Fluxo de pedidos': 'Flux des commandes', 'Distribuição dos pedidos no recorte atual.': 'Répartition des commandes pour la sélection.', Plataforma: 'Plateforme', 'Dimensão atual da base.': 'Taille actuelle de la plateforme.', Admins: 'Admins', 'Evolução do faturamento': 'Évolution du chiffre d’affaires', 'Receita, volume de pedidos e ticket médio.': 'Recettes, commandes et panier moyen.', Diário: 'Quotidien', Semanal: 'Hebdomadaire', Mensal: 'Mensuel', Receita: 'Recettes', 'Atividade recente': 'Activité récente', 'Movimentações mais relevantes da plataforma.': 'Activités les plus importantes de la plateforme.', 'Novo usuário cadastrado': 'Nouvel utilisateur inscrit',
    'Acompanhe os principais números e a atividade da plataforma.': 'Suivez les principaux chiffres et l’activité de la plateforme.', 'Gerencie acessos, perfis e permissões administrativas.': 'Gérez les accès, profils et autorisations.', 'Consulte e modere os anúncios publicados no catálogo.': 'Consultez et modérez les annonces du catalogue.', 'Acompanhe pedidos e atualize o andamento das transações.': 'Suivez les commandes et mettez à jour les transactions.', 'Modere as avaliações enviadas pela comunidade.': 'Modérez les avis envoyés par la communauté.',
    Buscar: 'Rechercher', Usuário: 'Utilisateur', Perfil: 'Profil', Cadastro: 'Inscription', Permissão: 'Autorisation', Ações: 'Actions', 'Tornar admin': 'Rendre admin', Cliente: 'Client', Valor: 'Montant', Produtos: 'Produits', Fornecedores: 'Fournisseurs', Nota: 'Note', Comentário: 'Commentaire', Data: 'Date', Pedido: 'Commande', Estoque: 'Stock', Preço: 'Prix', Cancelar: 'Annuler', 'Salvar alterações': 'Enregistrer', 'Criar administrador': 'Créer l’administrateur', 'Nome completo': 'Nom complet', Senha: 'Mot de passe', Telefone: 'Téléphone', 'Nome da loja': 'Nom de la boutique', 'Esta ação não poderá ser desfeita.': 'Cette action est irréversible.', 'Sim, excluir': 'Oui, supprimer',
    'Gerenciamento de acesso': 'Gestion des accès', 'Crie uma conta verificada com acesso imediato ao painel.': 'Créez un compte vérifié avec un accès immédiat au panneau.', 'Senha temporária': 'Mot de passe temporaire', 'Mínimo de 8 caracteres, contendo letras e números.': 'Au moins 8 caractères, avec des lettres et des chiffres.', 'Criando…': 'Création…', 'Edição administrativa': 'Modification administrative', Editar: 'Modifier', usuário: 'utilisateur', peça: 'pièce', avaliação: 'avis', 'Revise os dados antes de salvar a alteração.': 'Vérifiez les informations avant d’enregistrer.', 'O e-mail de acesso também será atualizado.': 'L’adresse e-mail de connexion sera également mise à jour.', 'Nome da peça': 'Nom de la pièce', estrela: 'étoile', estrelas: 'étoiles', 'Sem comentário': 'Sans commentaire',
    'Total de contas ativas cadastradas na plataforma.': 'Nombre total de comptes actifs sur la plateforme.', 'Contas que possuem acesso ao painel administrativo.': 'Comptes ayant accès au panneau d’administration.', 'Total de anúncios de peças disponíveis no catálogo.': 'Nombre total d’annonces disponibles dans le catalogue.', 'Quantidade total de pedidos registrados na plataforma.': 'Nombre total de commandes enregistrées.', 'Pedidos que ainda aguardam pagamento ou ação operacional.': 'Commandes en attente de paiement ou d’une action.', 'Avaliações publicadas por compradores.': 'Avis publiés par les acheteurs.', 'Soma dos pedidos não cancelados no período e filtros selecionados.': 'Somme des commandes non annulées selon la période et les filtres.', 'Valor médio dos pedidos não cancelados no recorte atual.': 'Valeur moyenne des commandes non annulées.', 'Percentual de pedidos do período que foram entregues.': 'Pourcentage de commandes livrées sur la période.', 'Percentual de pedidos do período que foram cancelados.': 'Pourcentage de commandes annulées sur la période.',
  },
};

const EXTRA = {
  EN: {
    'Editar avaliação': 'Edit review', 'Excluir avaliação': 'Delete review', 'Remover peça?': 'Remove part?',
    'A peça será retirada permanentemente do catálogo.': 'The part will be permanently removed from the catalog.',
    'A nota e o comentário serão excluídos permanentemente.': 'The rating and comment will be permanently deleted.',
    'Excluir usuário?': 'Delete user?', 'A conta perderá o acesso imediatamente.': 'The account will lose access immediately.',
    'Excluir permanentemente': 'Delete permanently', 'Excluir usuário permanentemente?': 'Permanently delete user?',
    'A conta, o perfil e todos os dados relacionados serão apagados.': 'The account, profile and all related data will be deleted.',
    'Excluir peça permanentemente?': 'Permanently delete part?', 'A peça e todos os dados relacionados serão apagados do banco.': 'The part and all related data will be deleted from the database.',
  },
  FR: {
    'Editar avaliação': 'Modifier l’avis', 'Excluir avaliação': 'Supprimer l’avis', 'Remover avaliação?': 'Supprimer l’avis ?', 'Remover peça?': 'Supprimer la pièce ?',
    'A peça será retirada permanentemente do catálogo.': 'La pièce sera définitivement retirée du catalogue.',
    'A nota e o comentário serão excluídos permanentemente.': 'La note et le commentaire seront définitivement supprimés.',
    'Excluir usuário?': 'Supprimer l’utilisateur ?', 'A conta perderá o acesso imediatamente.': 'Le compte perdra immédiatement son accès.',
    'Excluir permanentemente': 'Supprimer définitivement', 'Excluir usuário permanentemente?': 'Supprimer définitivement l’utilisateur ?',
    'A conta, o perfil e todos os dados relacionados serão apagados.': 'Le compte, le profil et toutes les données associées seront supprimés.',
    'Excluir peça permanentemente?': 'Supprimer définitivement la pièce ?', 'A peça e todos os dados relacionados serão apagados do banco.': 'La pièce et toutes les données associées seront supprimées de la base.',
  },
};

export function createAdminTranslator(language) {
  return (text) => EXTRA[language]?.[text] || COPY[language]?.[text] || text;
}
