begin;

-- As tabelas antigas foram criadas pelo editor visual e podem não ter sequência
-- automática no bigint da chave primária. Garante IDs sem alterar instalações
-- que já usam identity/serial.
do $$
declare
  vendas_sem_default boolean;
  avaliacoes_sem_default boolean;
begin
  select column_default is null and is_identity = 'NO'
    into vendas_sem_default
    from information_schema.columns
   where table_schema = 'public' and table_name = 'vendas' and column_name = 'id';

  if coalesce(vendas_sem_default, false) then
    create sequence if not exists public.vendas_id_seq;
    alter sequence public.vendas_id_seq owned by public.vendas.id;
    perform setval(
      'public.vendas_id_seq',
      greatest(coalesce((select max(id) from public.vendas), 0) + 1, 1),
      false
    );
    alter table public.vendas alter column id set default nextval('public.vendas_id_seq');
  end if;

  select column_default is null and is_identity = 'NO'
    into avaliacoes_sem_default
    from information_schema.columns
   where table_schema = 'public'
     and table_name = 'avaliacoes_fornecedor'
     and column_name = 'id';

  if coalesce(avaliacoes_sem_default, false) then
    create sequence if not exists public.avaliacoes_fornecedor_id_seq;
    alter sequence public.avaliacoes_fornecedor_id_seq owned by public.avaliacoes_fornecedor.id;
    perform setval(
      'public.avaliacoes_fornecedor_id_seq',
      greatest(coalesce((select max(id) from public.avaliacoes_fornecedor), 0) + 1, 1),
      false
    );
    alter table public.avaliacoes_fornecedor
      alter column id set default nextval('public.avaliacoes_fornecedor_id_seq');
  end if;
end $$;

-- Liga cada registro financeiro ao item que o originou no pedido. Isso permite
-- validar a compra sem confiar em IDs enviados pelo navegador.
alter table public.vendas
  add column if not exists pedido_id text;

alter table public.vendas
  add column if not exists item_indice integer;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'vendas_pedido_id_fkey'
  ) then
    alter table public.vendas
      add constraint vendas_pedido_id_fkey
      foreign key (pedido_id) references public.pedidos(id) on delete cascade;
  end if;
end $$;

create unique index if not exists vendas_pedido_item_uidx
  on public.vendas (pedido_id, item_indice);

alter table public.avaliacoes_fornecedor
  add column if not exists pedido_id text;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'avaliacoes_fornecedor_pedido_id_fkey'
  ) then
    alter table public.avaliacoes_fornecedor
      add constraint avaliacoes_fornecedor_pedido_id_fkey
      foreign key (pedido_id) references public.pedidos(id) on delete cascade;
  end if;
end $$;

create unique index if not exists avaliacoes_fornecedor_compra_uidx
  on public.avaliacoes_fornecedor (pedido_id, fornecedor_id, comprador_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'avaliacoes_fornecedor_nota_check'
  ) then
    alter table public.avaliacoes_fornecedor
      add constraint avaliacoes_fornecedor_nota_check check (nota between 1 and 5);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'avaliacoes_fornecedor_criterios_check'
  ) then
    alter table public.avaliacoes_fornecedor
      add constraint avaliacoes_fornecedor_criterios_check check (
        qualidade_peca between 1 and 5
        and comunicacao between 1 and 5
        and rapidez_entrega between 1 and 5
        and embalagem between 1 and 5
      );
  end if;
end $$;

create table if not exists public.avaliacoes_produto (
  id bigint generated by default as identity primary key,
  pedido_id text not null references public.pedidos(id) on delete cascade,
  venda_id bigint not null references public.vendas(id) on delete cascade,
  peca_id bigint not null references public.pecas(id) on delete cascade,
  fornecedor_id bigint not null references public.users(id) on delete cascade,
  comprador_id bigint not null references public.users(id) on delete cascade,
  nota integer not null check (nota between 1 and 5),
  comentario text,
  verificada boolean not null default true,
  data_avaliacao timestamp with time zone not null default now(),
  constraint avaliacoes_produto_compra_unique
    unique (pedido_id, venda_id, comprador_id)
);

create index if not exists avaliacoes_produto_peca_idx
  on public.avaliacoes_produto (peca_id, data_avaliacao desc);

create index if not exists avaliacoes_fornecedor_fornecedor_idx
  on public.avaliacoes_fornecedor (fornecedor_id, data_avaliacao desc);

-- A aplicação acessa essas tabelas exclusivamente pelo backend com service role.
-- Ativar RLS impede gravações diretas pelo cliente usando a chave anônima.
alter table public.avaliacoes_fornecedor enable row level security;
alter table public.avaliacoes_produto enable row level security;

commit;
