BEGIN;
SET LOCAL search_path = public, pg_temp;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';
DO $guard$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','f')) THEN
    RAISE EXCEPTION 'BLOQUEADO: public nao esta vazio. Nao use este bootstrap em producao nem o reexecute.';
  END IF;
  IF EXISTS (SELECT 1 FROM auth.users) THEN
    RAISE EXCEPTION 'BLOQUEADO: existem usuarios Auth. Este bootstrap exige um projeto novo.';
  END IF;
END $guard$;

CREATE TABLE public."admin_dashboard_preferences" (
  "user_id" bigint NOT NULL,
  "config" jsonb DEFAULT '{"widgets": ["usuarios", "pecas", "pedidos", "pedidos_pendentes", "avaliacoes"]}'::jsonb NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."avaliacoes_fornecedor" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "fornecedor_id" bigint NOT NULL,
  "comprador_id" bigint NOT NULL,
  "venda_id" bigint,
  "nota" integer NOT NULL,
  "comentario" text,
  "qualidade_peca" integer,
  "comunicacao" integer,
  "rapidez_entrega" integer,
  "embalagem" integer,
  "verificada" boolean DEFAULT false,
  "data_avaliacao" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "pedido_id" text
);

CREATE TABLE public."avaliacoes_pecas" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "peca_id" bigint NOT NULL,
  "revisao" integer NOT NULL,
  "avaliador_id" bigint,
  "status" text DEFAULT 'pendente'::text NOT NULL,
  "criterios_snapshot" jsonb NOT NULL,
  "respostas" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "comentarios" text,
  "criada_em" timestamp with time zone DEFAULT now() NOT NULL,
  "decidida_em" timestamp with time zone
);

CREATE TABLE public."avaliacoes_produto" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pedido_id" text NOT NULL,
  "venda_id" bigint NOT NULL,
  "peca_id" bigint NOT NULL,
  "fornecedor_id" bigint NOT NULL,
  "comprador_id" bigint NOT NULL,
  "nota" integer NOT NULL,
  "comentario" text,
  "verificada" boolean DEFAULT true NOT NULL,
  "data_avaliacao" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."categorias" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "nome" character varying NOT NULL
);

CREATE TABLE public."checklist_validacao_peca" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "nome_criterio" character varying NOT NULL,
  "descricao" text,
  "obrigatorio" boolean DEFAULT true NOT NULL,
  "ativo" boolean DEFAULT true NOT NULL,
  "ordem" integer DEFAULT 0 NOT NULL,
  "criado_em" timestamp with time zone DEFAULT now(),
  "atualizado_em" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."marcas" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "nome" character varying NOT NULL
);

CREATE TABLE public."materiais" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "nome" character varying NOT NULL
);

CREATE TABLE public."mensagens" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "id_remetente" bigint,
  "id_destinatario" bigint,
  "mensagem" text
);

CREATE TABLE public."modelos" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "marca_id" bigint NOT NULL,
  "nome" character varying NOT NULL
);

CREATE TABLE public."notificacoes" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" text NOT NULL,
  "pedido_id" text,
  "tipo" text NOT NULL,
  "titulo" text NOT NULL,
  "mensagem" text NOT NULL,
  "status_envio" text DEFAULT 'pendente'::text NOT NULL,
  "lida_em" timestamp with time zone,
  "criada_em" timestamp with time zone DEFAULT now() NOT NULL,
  "email_destino" text,
  "peca_id" bigint
);

CREATE TABLE public."parcelas_venda" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "venda_id" bigint NOT NULL,
  "numero_parcela" integer NOT NULL,
  "valor_parcela" numeric NOT NULL,
  "valor_pago" numeric DEFAULT 0,
  "data_vencimento" date NOT NULL,
  "data_pagamento" date,
  "status" character varying DEFAULT 'pendente'::character varying
);

CREATE TABLE public."peca_compatibilidade" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "peca_id" bigint NOT NULL,
  "modelo_id" bigint NOT NULL,
  "ano_inicio" integer,
  "ano_fim" integer,
  "observacao_ajuste" character varying
);

CREATE TABLE public."pecas" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome_peca" character varying NOT NULL,
  "sku" character varying,
  "oem_number" character varying,
  "num_serie" character varying,
  "categoria_id" bigint,
  "material_id" bigint,
  "condicao" character varying,
  "peso_gramas" integer,
  "comprimento_mm" integer,
  "largura_mm" integer,
  "altura_mm" integer,
  "detalhes_gravacao" text,
  "historico_proveniencia" text,
  "fornecedor_id" bigint NOT NULL,
  "preco" numeric NOT NULL,
  "estoque_atual" integer DEFAULT 0,
  "status" character varying DEFAULT 'disponivel'::character varying,
  "data_cadastro" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "imagem" text,
  "fabricante" character varying,
  "status_publicacao" character varying DEFAULT 'pendente_validacao'::character varying,
  "url_video" text,
  "motivo_rejeicao" text,
  "dados_api_validacao" jsonb,
  "status_api_serie" character varying DEFAULT 'nao_verificado'::character varying NOT NULL,
  "verificado_serie_em" timestamp with time zone,
  "requer_revalidacao" boolean DEFAULT false NOT NULL,
  "revisao_avaliacao" integer DEFAULT 1 NOT NULL,
  "publicada_em" timestamp with time zone,
  "moeda_base" character varying DEFAULT 'BRL'::character varying NOT NULL,
  "preco_base" numeric NOT NULL
);

CREATE TABLE public."pedidos" (
  "id" text NOT NULL,
  "user_id" bigint NOT NULL,
  "status" text DEFAULT 'aguardando_pagamento'::text NOT NULL,
  "itens" jsonb NOT NULL,
  "frete" jsonb,
  "cupom" jsonb,
  "endereco" jsonb NOT NULL,
  "forma_pagamento" jsonb NOT NULL,
  "subtotal" numeric NOT NULL,
  "desconto" numeric DEFAULT 0,
  "valor_frete" numeric DEFAULT 0,
  "total" numeric NOT NULL,
  "codigo_rastreio" text,
  "historico" jsonb DEFAULT '[]'::jsonb,
  "criado_em" timestamp with time zone DEFAULT now(),
  "data_preferida" date,
  "urgencia_entrega" text
);

CREATE TABLE public."taxas_cambio" (
  "moeda" character varying NOT NULL,
  "unidades_por_brl" numeric,
  "atualizado_em" timestamp with time zone DEFAULT now() NOT NULL,
  "fonte" text DEFAULT 'configuracao'::text NOT NULL
);

CREATE TABLE public."users" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "email" character varying NOT NULL,
  "full_name" character varying NOT NULL,
  "gender" character varying,
  "cep" character varying,
  "tipo_usuario" character varying DEFAULT 'comprador'::character varying,
  "nome_loja" character varying,
  "descricao_loja" text,
  "telefone" character varying,
  "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "email_verificado" boolean DEFAULT false,
  "time_futebol" text,
  "sabor_pizza" text,
  "receber_email_notificacao_venda" boolean DEFAULT true NOT NULL,
  "is_admin" boolean DEFAULT false NOT NULL,
  "moeda_padrao" character varying DEFAULT 'BRL'::character varying,
  "pais_origem" character varying DEFAULT 'BR'::character varying
);

CREATE TABLE public."vendas" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "peca_id" bigint NOT NULL,
  "fornecedor_id" bigint NOT NULL,
  "comprador_id" bigint NOT NULL,
  "quantidade" integer DEFAULT 1,
  "preco_unitario" numeric NOT NULL,
  "preco_total" numeric NOT NULL,
  "forma_pagamento" character varying NOT NULL,
  "parcelado" boolean DEFAULT false,
  "numero_parcelas" integer DEFAULT 1,
  "primeira_parcela_data" date,
  "juros_percentual" numeric DEFAULT 0,
  "status" character varying DEFAULT 'pendente'::character varying,
  "data_venda" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "data_entrega" timestamp without time zone,
  "cancelled_at" timestamp without time zone,
  "pedido_id" text,
  "item_indice" integer
);

CREATE TABLE public."wishlist" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "peca_id" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER SEQUENCE public.wishlist_id_seq RENAME TO whitelist_id_seq;

ALTER TABLE public."pecas" ADD CONSTRAINT "pecas_sku_key" UNIQUE (sku);
ALTER TABLE public."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY (id);
ALTER TABLE public."users" ADD CONSTRAINT "users_email_key" UNIQUE (email);
ALTER TABLE public."marcas" ADD CONSTRAINT "marcas_pkey" PRIMARY KEY (id);
ALTER TABLE public."marcas" ADD CONSTRAINT "marcas_nome_key" UNIQUE (nome);
ALTER TABLE public."modelos" ADD CONSTRAINT "modelos_pkey" PRIMARY KEY (id);
ALTER TABLE public."categorias" ADD CONSTRAINT "categorias_pkey" PRIMARY KEY (id);
ALTER TABLE public."categorias" ADD CONSTRAINT "categorias_nome_key" UNIQUE (nome);
ALTER TABLE public."materiais" ADD CONSTRAINT "materiais_pkey" PRIMARY KEY (id);
ALTER TABLE public."materiais" ADD CONSTRAINT "materiais_nome_key" UNIQUE (nome);
ALTER TABLE public."pecas" ADD CONSTRAINT "pecas_pkey" PRIMARY KEY (id);
ALTER TABLE public."peca_compatibilidade" ADD CONSTRAINT "peca_compatibilidade_pkey" PRIMARY KEY (id);
ALTER TABLE public."vendas" ADD CONSTRAINT "vendas_pkey" PRIMARY KEY (id);
ALTER TABLE public."parcelas_venda" ADD CONSTRAINT "parcelas_venda_pkey" PRIMARY KEY (id);
ALTER TABLE public."parcelas_venda" ADD CONSTRAINT "parcelas_venda_venda_id_numero_parcela_key" UNIQUE (venda_id, numero_parcela);
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_nota_check" CHECK (((nota >= 1) AND (nota <= 5)));
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_qualidade_peca_check" CHECK (((qualidade_peca >= 1) AND (qualidade_peca <= 5)));
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_comunicacao_check" CHECK (((comunicacao >= 1) AND (comunicacao <= 5)));
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_rapidez_entrega_check" CHECK (((rapidez_entrega >= 1) AND (rapidez_entrega <= 5)));
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_embalagem_check" CHECK (((embalagem >= 1) AND (embalagem <= 5)));
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_pkey" PRIMARY KEY (id);
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_venda_id_key" UNIQUE (venda_id);
ALTER TABLE public."wishlist" ADD CONSTRAINT "wishlist_user_peca_unique" UNIQUE (user_id, peca_id);
ALTER TABLE public."wishlist" ADD CONSTRAINT "wishlist_pkey" PRIMARY KEY (id);
ALTER TABLE public."mensagens" ADD CONSTRAINT "mensagens_pkey" PRIMARY KEY (id);
ALTER TABLE public."pedidos" ADD CONSTRAINT "pedidos_pkey" PRIMARY KEY (id);
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_criterios_check" CHECK ((((qualidade_peca >= 1) AND (qualidade_peca <= 5)) AND ((comunicacao >= 1) AND (comunicacao <= 5)) AND ((rapidez_entrega >= 1) AND (rapidez_entrega <= 5)) AND ((embalagem >= 1) AND (embalagem <= 5))));
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_nota_check" CHECK (((nota >= 1) AND (nota <= 5)));
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_pkey" PRIMARY KEY (id);
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_compra_unique" UNIQUE (pedido_id, venda_id, comprador_id);
ALTER TABLE public."admin_dashboard_preferences" ADD CONSTRAINT "admin_dashboard_preferences_pkey" PRIMARY KEY (user_id);
ALTER TABLE public."notificacoes" ADD CONSTRAINT "notificacoes_pkey" PRIMARY KEY (id);
ALTER TABLE public."checklist_validacao_peca" ADD CONSTRAINT "checklist_validacao_peca_pkey" PRIMARY KEY (id);
ALTER TABLE public."avaliacoes_pecas" ADD CONSTRAINT "avaliacoes_pecas_revisao_check" CHECK ((revisao > 0));
ALTER TABLE public."avaliacoes_pecas" ADD CONSTRAINT "avaliacoes_pecas_status_check" CHECK ((status = ANY (ARRAY['pendente'::text, 'aprovada'::text, 'rejeitada'::text, 'substituida'::text])));
ALTER TABLE public."avaliacoes_pecas" ADD CONSTRAINT "avaliacoes_pecas_criterios_snapshot_check" CHECK ((jsonb_typeof(criterios_snapshot) = 'array'::text));
ALTER TABLE public."avaliacoes_pecas" ADD CONSTRAINT "avaliacoes_pecas_pkey" PRIMARY KEY (id);
ALTER TABLE public."avaliacoes_pecas" ADD CONSTRAINT "avaliacoes_pecas_peca_id_revisao_key" UNIQUE (peca_id, revisao);
ALTER TABLE public."taxas_cambio" ADD CONSTRAINT "taxas_cambio_moeda_check" CHECK (((moeda)::text ~ '^[A-Z]{3}$'::text));
ALTER TABLE public."taxas_cambio" ADD CONSTRAINT "taxas_cambio_unidades_por_brl_check" CHECK ((unidades_por_brl > (0)::numeric));
ALTER TABLE public."taxas_cambio" ADD CONSTRAINT "taxas_cambio_check" CHECK ((((moeda)::text <> 'BRL'::text) OR (unidades_por_brl = (1)::numeric)));
ALTER TABLE public."taxas_cambio" ADD CONSTRAINT "taxas_cambio_pkey" PRIMARY KEY (moeda);
ALTER TABLE public."pecas" ADD CONSTRAINT "pecas_api_serie_status_check" CHECK (((status_api_serie)::text = ANY ((ARRAY['nao_verificado'::character varying, 'pendente'::character varying, 'aprovado'::character varying, 'reprovado'::character varying, 'erro'::character varying])::text[]))) NOT VALID;
ALTER TABLE public."modelos" ADD CONSTRAINT "modelos_marca_id_fkey" FOREIGN KEY (marca_id) REFERENCES marcas(id);
ALTER TABLE public."pecas" ADD CONSTRAINT "pecas_categoria_id_fkey" FOREIGN KEY (categoria_id) REFERENCES categorias(id);
ALTER TABLE public."pecas" ADD CONSTRAINT "pecas_material_id_fkey" FOREIGN KEY (material_id) REFERENCES materiais(id);
ALTER TABLE public."pecas" ADD CONSTRAINT "pecas_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public."peca_compatibilidade" ADD CONSTRAINT "peca_compatibilidade_peca_id_fkey" FOREIGN KEY (peca_id) REFERENCES pecas(id) ON DELETE CASCADE;
ALTER TABLE public."peca_compatibilidade" ADD CONSTRAINT "peca_compatibilidade_modelo_id_fkey" FOREIGN KEY (modelo_id) REFERENCES modelos(id);
ALTER TABLE public."vendas" ADD CONSTRAINT "vendas_peca_id_fkey" FOREIGN KEY (peca_id) REFERENCES pecas(id);
ALTER TABLE public."vendas" ADD CONSTRAINT "vendas_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES users(id);
ALTER TABLE public."vendas" ADD CONSTRAINT "vendas_comprador_id_fkey" FOREIGN KEY (comprador_id) REFERENCES users(id);
ALTER TABLE public."parcelas_venda" ADD CONSTRAINT "parcelas_venda_venda_id_fkey" FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_comprador_id_fkey" FOREIGN KEY (comprador_id) REFERENCES users(id);
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_venda_id_fkey" FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE SET NULL;
ALTER TABLE public."wishlist" ADD CONSTRAINT "whitelist_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public."wishlist" ADD CONSTRAINT "whitelist_peca_id_fkey" FOREIGN KEY (peca_id) REFERENCES pecas(id) ON DELETE CASCADE;
ALTER TABLE public."pedidos" ADD CONSTRAINT "pedidos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_comprador_id_fkey" FOREIGN KEY (comprador_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public."admin_dashboard_preferences" ADD CONSTRAINT "admin_dashboard_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public."vendas" ADD CONSTRAINT "vendas_pedido_id_fkey" FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_fornecedor" ADD CONSTRAINT "avaliacoes_fornecedor_pedido_id_fkey" FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_pedido_id_fkey" FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_venda_id_fkey" FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE CASCADE;
ALTER TABLE public."avaliacoes_produto" ADD CONSTRAINT "avaliacoes_produto_peca_id_fkey" FOREIGN KEY (peca_id) REFERENCES pecas(id) ON DELETE CASCADE;
ALTER TABLE public."notificacoes" ADD CONSTRAINT "notificacoes_peca_id_fkey" FOREIGN KEY (peca_id) REFERENCES pecas(id) ON DELETE SET NULL;
ALTER TABLE public."avaliacoes_pecas" ADD CONSTRAINT "avaliacoes_pecas_peca_id_fkey" FOREIGN KEY (peca_id) REFERENCES pecas(id);
ALTER TABLE public."avaliacoes_pecas" ADD CONSTRAINT "avaliacoes_pecas_avaliador_id_fkey" FOREIGN KEY (avaliador_id) REFERENCES users(id);
CREATE INDEX users_is_admin_idx ON public.users USING btree (is_admin) WHERE (is_admin = true);
CREATE INDEX avaliacoes_produto_peca_idx ON public.avaliacoes_produto USING btree (peca_id, data_avaliacao DESC);
CREATE INDEX idx_parcelas_venda ON public.parcelas_venda USING btree (venda_id);
CREATE INDEX idx_parcelas_status ON public.parcelas_venda USING btree (status);
CREATE INDEX idx_vendas_fornecedor ON public.vendas USING btree (fornecedor_id);
CREATE INDEX idx_vendas_comprador ON public.vendas USING btree (comprador_id);
CREATE INDEX idx_vendas_peca ON public.vendas USING btree (peca_id);
CREATE INDEX idx_vendas_status ON public.vendas USING btree (status);
CREATE UNIQUE INDEX vendas_pedido_item_uidx ON public.vendas USING btree (pedido_id, item_indice);
CREATE INDEX idx_avaliacoes_fornecedor ON public.avaliacoes_fornecedor USING btree (fornecedor_id);
CREATE INDEX idx_avaliacoes_comprador ON public.avaliacoes_fornecedor USING btree (comprador_id);
CREATE UNIQUE INDEX avaliacoes_fornecedor_compra_uidx ON public.avaliacoes_fornecedor USING btree (pedido_id, fornecedor_id, comprador_id);
CREATE INDEX avaliacoes_fornecedor_fornecedor_idx ON public.avaliacoes_fornecedor USING btree (fornecedor_id, data_avaliacao DESC);
CREATE INDEX wishlist_user_id_idx ON public.wishlist USING btree (user_id);
CREATE INDEX wishlist_peca_id_idx ON public.wishlist USING btree (peca_id);
CREATE INDEX idx_avaliacoes_pecas_avaliador ON public.avaliacoes_pecas USING btree (avaliador_id);
CREATE INDEX idx_pecas_fornecedor ON public.pecas USING btree (fornecedor_id);
CREATE INDEX idx_pecas_categoria ON public.pecas USING btree (categoria_id);
CREATE INDEX idx_pecas_status ON public.pecas USING btree (status);
CREATE INDEX idx_pecas_fila ON public.pecas USING btree (status_publicacao, data_cadastro);

CREATE OR REPLACE FUNCTION public.atualizar_preco_total_venda()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.preco_total := NEW.quantidade * NEW.preco_unitario;
    IF NEW.parcelado AND NEW.numero_parcelas > 0 THEN
        NEW.preco_total := NEW.preco_total * (1 + NEW.juros_percentual / 100);
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.decidir_avaliacao_peca(p_peca bigint, p_avaliador bigint, p_revisao integer, p_respostas jsonb, p_comentarios text DEFAULT ''::text, p_rejeitar boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE p public.pecas; a public.avaliacoes_pecas; c jsonb; r jsonb; aprovada boolean;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id=p_avaliador AND (tipo_usuario='avaliador' OR is_admin)) THEN
    RAISE EXCEPTION 'Usuário sem permissão para avaliar.';
  END IF;
  SELECT * INTO p FROM public.pecas WHERE id=p_peca FOR UPDATE;
  IF NOT FOUND OR p.status_publicacao <> 'pendente_validacao' OR p.revisao_avaliacao <> p_revisao THEN
    RAISE EXCEPTION 'O anúncio mudou ou já foi avaliado. Recarregue a fila.';
  END IF;
  IF p.fornecedor_id=p_avaliador THEN RAISE EXCEPTION 'Não é permitido avaliar o próprio anúncio.'; END IF;
  SELECT * INTO a FROM public.avaliacoes_pecas WHERE peca_id=p_peca AND revisao=p_revisao FOR UPDATE;
  IF NOT FOUND OR a.status <> 'pendente' THEN RAISE EXCEPTION 'Avaliação indisponível.'; END IF;
  IF jsonb_typeof(p_respostas) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Checklist inválido.'; END IF;
  IF jsonb_array_length(p_respostas) <> jsonb_array_length(a.criterios_snapshot) THEN
    RAISE EXCEPTION 'Responda todos os critérios desta revisão.';
  END IF;
  IF EXISTS (SELECT 1 FROM jsonb_array_elements(p_respostas) x
    GROUP BY x->>'criterio_id' HAVING count(*)>1) THEN RAISE EXCEPTION 'Critérios duplicados.'; END IF;
  aprovada := jsonb_array_length(a.criterios_snapshot)>0;
  FOR c IN SELECT * FROM jsonb_array_elements(a.criterios_snapshot) LOOP
    SELECT x INTO r FROM jsonb_array_elements(p_respostas) x WHERE x->>'criterio_id'=c->>'id';
    IF r IS NULL OR jsonb_typeof(r->'resposta') IS DISTINCT FROM 'boolean' THEN
      RAISE EXCEPTION 'Resposta ausente ou inválida.';
    END IF;
    IF (c->>'obrigatorio')::boolean AND NOT (r->>'resposta')::boolean THEN aprovada:=false; END IF;
  END LOOP;
  IF p_rejeitar THEN
    IF length(trim(COALESCE(p_comentarios,'')))=0 THEN RAISE EXCEPTION 'Informe o motivo da reprovação.'; END IF;
    aprovada:=false;
  ELSIF NOT aprovada THEN
    RAISE EXCEPTION 'Marque positivamente todos os critérios obrigatórios ou reprove com motivo.';
  END IF;
  UPDATE public.avaliacoes_pecas SET avaliador_id=p_avaliador, respostas=p_respostas,
    comentarios=p_comentarios, decidida_em=now(), status=CASE WHEN aprovada THEN 'aprovada' ELSE 'rejeitada' END
    WHERE id=a.id;
  UPDATE public.pecas SET status_publicacao=CASE WHEN aprovada THEN 'publicada' ELSE 'rejeitada' END,
    publicada_em=CASE WHEN aprovada THEN now() ELSE NULL END,
    motivo_rejeicao=CASE WHEN aprovada THEN NULL ELSE p_comentarios END, requer_revalidacao=NOT aprovada
    WHERE id=p_peca;
  INSERT INTO public.notificacoes(user_id,tipo,titulo,mensagem,status_envio,peca_id)
    VALUES (p.fornecedor_id::text,CASE WHEN aprovada THEN 'validacao_aprovada' ELSE 'validacao_rejeitada' END,
      CASE WHEN aprovada THEN 'Peça aprovada e publicada' ELSE 'Peça reprovada' END,
      CASE WHEN aprovada THEN 'Seu anúncio está disponível no catálogo.' ELSE p_comentarios END,'enviada',p_peca);
  RETURN jsonb_build_object('publicada',aprovada,'status',CASE WHEN aprovada THEN 'aprovada' ELSE 'rejeitada' END);
END $function$;

CREATE OR REPLACE FUNCTION public.enfileirar_avaliacao_peca()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.revisao_avaliacao = OLD.revisao_avaliacao THEN RETURN NEW; END IF;
    UPDATE public.avaliacoes_pecas SET status='substituida'
      WHERE peca_id=NEW.id AND status='pendente';
  END IF;
  INSERT INTO public.avaliacoes_pecas(peca_id, revisao, criterios_snapshot)
    VALUES (NEW.id, NEW.revisao_avaliacao, public.snapshot_checklist_peca());
  INSERT INTO public.notificacoes(user_id, tipo, titulo, mensagem, status_envio, peca_id)
    SELECT id::text, 'nova_peca_para_validar', 'Nova peça aguardando avaliação',
      'Avalie o anúncio: ' || NEW.nome_peca, 'enviada', NEW.id
    FROM public.users WHERE tipo_usuario='avaliador' AND id <> NEW.fornecedor_id;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.excluir_peca_permanentemente(p_peca_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE afetadas bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.pecas WHERE id = p_peca_id) THEN RETURN false; END IF;
  PERFORM set_config('app.exclusao_permanente', 'on', true);

  UPDATE public.notificacoes SET peca_id = NULL WHERE peca_id = p_peca_id;
  DELETE FROM public.avaliacoes_produto WHERE peca_id = p_peca_id
    OR venda_id IN (SELECT id FROM public.vendas WHERE peca_id = p_peca_id);
  DELETE FROM public.avaliacoes_fornecedor WHERE venda_id IN (SELECT id FROM public.vendas WHERE peca_id = p_peca_id);
  DELETE FROM public.parcelas_venda WHERE venda_id IN (SELECT id FROM public.vendas WHERE peca_id = p_peca_id);
  DELETE FROM public.vendas WHERE peca_id = p_peca_id;
  DELETE FROM public.wishlist WHERE peca_id = p_peca_id;
  DELETE FROM public.peca_compatibilidade WHERE peca_id = p_peca_id;
  -- Estruturas do protótipo antigo podem não existir no schema atual.
  IF to_regclass('public.faixas_preco') IS NOT NULL THEN
    EXECUTE 'DELETE FROM public.faixas_preco WHERE peca_id = $1' USING p_peca_id;
  END IF;
  IF to_regclass('public.validacao_peca') IS NOT NULL THEN
    IF to_regclass('public.checklist_respostas_validacao') IS NOT NULL THEN
      EXECUTE 'DELETE FROM public.checklist_respostas_validacao WHERE validacao_id IN
        (SELECT id FROM public.validacao_peca WHERE peca_id = $1)' USING p_peca_id;
    END IF;
    EXECUTE 'DELETE FROM public.validacao_peca WHERE peca_id = $1' USING p_peca_id;
  END IF;
  DELETE FROM public.avaliacoes_pecas WHERE peca_id = p_peca_id;
  DELETE FROM public.pecas WHERE id = p_peca_id;
  GET DIAGNOSTICS afetadas = ROW_COUNT;
  RETURN afetadas > 0;
END $function$;

CREATE OR REPLACE FUNCTION public.excluir_usuario_permanentemente(p_usuario_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE p record; afetadas bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id = p_usuario_id) THEN RETURN false; END IF;
  PERFORM set_config('app.exclusao_permanente', 'on', true);

  FOR p IN SELECT id FROM public.pecas WHERE fornecedor_id = p_usuario_id LOOP
    PERFORM public.excluir_peca_permanentemente(p.id);
  END LOOP;

  DELETE FROM public.avaliacoes_produto WHERE comprador_id = p_usuario_id OR fornecedor_id = p_usuario_id
    OR venda_id IN (SELECT id FROM public.vendas WHERE comprador_id = p_usuario_id OR fornecedor_id = p_usuario_id)
    OR pedido_id IN (SELECT id FROM public.pedidos WHERE user_id = p_usuario_id);
  DELETE FROM public.avaliacoes_fornecedor WHERE comprador_id = p_usuario_id OR fornecedor_id = p_usuario_id
    OR venda_id IN (SELECT id FROM public.vendas WHERE comprador_id = p_usuario_id OR fornecedor_id = p_usuario_id)
    OR pedido_id IN (SELECT id FROM public.pedidos WHERE user_id = p_usuario_id);
  DELETE FROM public.parcelas_venda WHERE venda_id IN
    (SELECT id FROM public.vendas WHERE comprador_id = p_usuario_id OR fornecedor_id = p_usuario_id
      OR pedido_id IN (SELECT id FROM public.pedidos WHERE user_id = p_usuario_id));
  DELETE FROM public.vendas WHERE comprador_id = p_usuario_id OR fornecedor_id = p_usuario_id
    OR pedido_id IN (SELECT id FROM public.pedidos WHERE user_id = p_usuario_id);
  DELETE FROM public.pedidos WHERE user_id = p_usuario_id;
  DELETE FROM public.wishlist WHERE user_id = p_usuario_id;
  DELETE FROM public.admin_dashboard_preferences WHERE user_id = p_usuario_id;
  IF to_regclass('public.validacao_peca') IS NOT NULL THEN
    IF to_regclass('public.checklist_respostas_validacao') IS NOT NULL THEN
      EXECUTE 'DELETE FROM public.checklist_respostas_validacao WHERE validacao_id IN
        (SELECT id FROM public.validacao_peca WHERE avaliador_id = $1)' USING p_usuario_id;
    END IF;
    EXECUTE 'DELETE FROM public.validacao_peca WHERE avaliador_id = $1' USING p_usuario_id;
  END IF;
  UPDATE public.avaliacoes_pecas SET avaliador_id = NULL WHERE avaliador_id = p_usuario_id;
  DELETE FROM public.notificacoes WHERE user_id = p_usuario_id::text;
  DELETE FROM public.mensagens WHERE id_remetente = p_usuario_id OR id_destinatario = p_usuario_id;
  DELETE FROM public.users WHERE id = p_usuario_id;
  GET DIAGNOSTICS afetadas = ROW_COUNT;
  RETURN afetadas > 0;
END $function$;

CREATE OR REPLACE FUNCTION public.preparar_avaliacao_peca()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE taxa numeric; alterou boolean;
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.status_publicacao := 'pendente_validacao';
    NEW.revisao_avaliacao := 1;
    NEW.publicada_em := NULL;
    NEW.status_api_serie := 'nao_verificado';
    NEW.dados_api_validacao := NULL;
    NEW.verificado_serie_em := NULL;
  ELSE
    -- Estoque e campos internos de pagamento não invalidam a avaliação.
    alterou := (to_jsonb(NEW) - ARRAY['estoque_atual','status','updated_at','preco',
      'status_publicacao','revisao_avaliacao','publicada_em','motivo_rejeicao','requer_revalidacao',
      'status_api_serie','dados_api_validacao','verificado_serie_em'])
      IS DISTINCT FROM
      (to_jsonb(OLD) - ARRAY['estoque_atual','status','updated_at','preco',
      'status_publicacao','revisao_avaliacao','publicada_em','motivo_rejeicao','requer_revalidacao',
      'status_api_serie','dados_api_validacao','verificado_serie_em']);
    IF alterou THEN
      NEW.status_publicacao := 'pendente_validacao';
      NEW.revisao_avaliacao := OLD.revisao_avaliacao + 1;
      NEW.publicada_em := NULL;
      NEW.motivo_rejeicao := NULL;
      NEW.requer_revalidacao := true;
    END IF;
    IF NEW.num_serie IS DISTINCT FROM OLD.num_serie THEN
      NEW.status_api_serie := 'nao_verificado';
      NEW.dados_api_validacao := NULL;
      NEW.verificado_serie_em := NULL;
    END IF;
  END IF;
  NEW.moeda_base := upper(COALESCE(NEW.moeda_base, 'BRL'));
  NEW.preco_base := COALESCE(NEW.preco_base, NEW.preco);
  SELECT unidades_por_brl INTO taxa FROM public.taxas_cambio WHERE moeda = NEW.moeda_base;
  IF taxa IS NULL OR NEW.preco_base IS NULL OR NEW.preco_base <= 0 THEN
    RAISE EXCEPTION 'Preço ou moeda base inválidos; configure a taxa de câmbio.';
  END IF;
  -- preco legado continua em BRL para pedidos, frete e vendas existentes.
  NEW.preco := round(NEW.preco_base / taxa, 2);
  IF NEW.status_publicacao = 'publicada' AND NOT EXISTS (
    SELECT 1 FROM public.avaliacoes_pecas WHERE peca_id = NEW.id
      AND revisao = NEW.revisao_avaliacao AND status = 'aprovada'
  ) THEN RAISE EXCEPTION 'Publicação exige uma avaliação aprovada da revisão atual.'; END IF;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.proteger_historico_avaliacao()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF current_setting('app.exclusao_permanente', true) = 'on' THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'O histórico de avaliação não pode ser excluído.'; END IF;
  IF NEW.criterios_snapshot IS DISTINCT FROM OLD.criterios_snapshot OR
     NEW.peca_id IS DISTINCT FROM OLD.peca_id OR NEW.revisao IS DISTINCT FROM OLD.revisao OR
     OLD.status <> 'pendente' THEN
    RAISE EXCEPTION 'O histórico de avaliação é imutável. Crie uma nova revisão.';
  END IF;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.proteger_is_admin()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if new.is_admin is distinct from old.is_admin
     and current_user not in ('postgres', 'service_role', 'supabase_admin') then
    raise exception 'A permissao administrativa so pode ser alterada pelo backend administrativo.'
      using errcode = '42501';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.snapshot_checklist_peca()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public', 'pg_temp'
AS $function$
 SELECT COALESCE(jsonb_agg(jsonb_build_object(
  'id', id, 'nome_criterio', nome_criterio, 'descricao', descricao,
  'obrigatorio', COALESCE(obrigatorio,true), 'ordem', ordem) ORDER BY ordem NULLS LAST, id), '[]'::jsonb)
 FROM public.checklist_validacao_peca WHERE ativo = true
$function$;

CREATE TRIGGER proteger_historico_avaliacao BEFORE DELETE OR UPDATE ON public.avaliacoes_pecas FOR EACH ROW EXECUTE FUNCTION proteger_historico_avaliacao();

CREATE TRIGGER enfileirar_avaliacao_peca AFTER INSERT OR UPDATE ON public.pecas FOR EACH ROW EXECUTE FUNCTION enfileirar_avaliacao_peca();

CREATE TRIGGER preparar_avaliacao_peca BEFORE INSERT OR UPDATE ON public.pecas FOR EACH ROW EXECUTE FUNCTION preparar_avaliacao_peca();

CREATE TRIGGER users_proteger_is_admin BEFORE UPDATE OF is_admin ON public.users FOR EACH ROW EXECUTE FUNCTION proteger_is_admin();

CREATE TRIGGER trigger_atualizar_preco_venda BEFORE INSERT OR UPDATE ON public.vendas FOR EACH ROW EXECUTE FUNCTION atualizar_preco_total_venda();

CREATE VIEW public."fornecedor_stats" AS
SELECT f.id,
    f.full_name,
    f.nome_loja,
    count(DISTINCT v.id) AS total_vendas,
    count(DISTINCT av.id) AS total_avaliacoes,
    round(avg(av.nota), 2) AS nota_media,
    count(DISTINCT p.id) AS total_pecas_ativas,
    sum(v.preco_total) AS total_vendido
   FROM (((users f
     LEFT JOIN vendas v ON (((f.id = v.fornecedor_id) AND ((v.status)::text <> 'cancelada'::text))))
     LEFT JOIN avaliacoes_fornecedor av ON ((f.id = av.fornecedor_id)))
     LEFT JOIN pecas p ON (((f.id = p.fornecedor_id) AND ((p.status)::text = 'disponivel'::text))))
  WHERE ((f.tipo_usuario)::text = ANY ((ARRAY['fornecedor'::character varying, 'ambos'::character varying])::text[]))
  GROUP BY f.id, f.full_name, f.nome_loja;

CREATE VIEW public."vendas_ativas" AS
SELECT v.id,
    p.nome_peca,
    f.full_name AS nome_fornecedor,
    c.full_name AS nome_comprador,
    v.preco_total,
    v.forma_pagamento,
    v.numero_parcelas,
    v.status,
    v.data_venda
   FROM (((vendas v
     JOIN pecas p ON ((v.peca_id = p.id)))
     JOIN users f ON ((v.fornecedor_id = f.id)))
     JOIN users c ON ((v.comprador_id = c.id)))
  WHERE ((v.status)::text = ANY ((ARRAY['pendente'::character varying, 'confirmada'::character varying])::text[]));

CREATE VIEW public."precos_publicos_moeda" AS
SELECT p.id,
    p.nome_peca,
    p.sku,
    p.oem_number,
    p.num_serie,
    p.categoria_id,
    p.material_id,
    p.condicao,
    p.peso_gramas,
    p.comprimento_mm,
    p.largura_mm,
    p.altura_mm,
    p.detalhes_gravacao,
    p.historico_proveniencia,
    p.fornecedor_id,
    p.preco,
    p.estoque_atual,
    p.status,
    p.data_cadastro,
    p.updated_at,
    p.imagem,
    p.fabricante,
    p.status_publicacao,
    p.url_video,
    p.motivo_rejeicao,
    p.dados_api_validacao,
    p.status_api_serie,
    p.verificado_serie_em,
    p.requer_revalidacao,
    p.revisao_avaliacao,
    p.publicada_em,
    p.moeda_base,
    p.preco_base,
    t.moeda AS moeda_exibicao,
    round(((p.preco_base / origem.unidades_por_brl) * t.unidades_por_brl), 2) AS preco_exibicao
   FROM ((pecas p
     JOIN taxas_cambio origem ON ((((origem.moeda)::text = (p.moeda_base)::text) AND (origem.unidades_por_brl IS NOT NULL))))
     CROSS JOIN taxas_cambio t)
  WHERE (((p.status_publicacao)::text = 'publicada'::text) AND (t.unidades_por_brl IS NOT NULL));

CREATE POLICY "bigpecas_publicadas_leitura" ON public."pecas" AS PERMISSIVE FOR SELECT TO "anon","authenticated" USING (((status_publicacao)::text = 'publicada'::text));

CREATE POLICY "bigpecas_publicadas_restricao" ON public."pecas" AS RESTRICTIVE FOR SELECT TO "anon","authenticated" USING (((status_publicacao)::text = 'publicada'::text));

-- Seguranca intencionalmente mais restrita que a exportacao de producao.
-- BEGIN SECURITY MIGRATION
-- PREPARADO PARA HOMOLOGACAO. NAO EXECUTADO EM PRODUCAO.
-- Aplicar primeiro no Dev/Qas e validar backend, Auth e chat.
-- Nao copia/apaga dados e nao altera colunas, contas Auth ou senhas.

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

DO $permissions$
DECLARE
  table_name text;
  column_name text;
  sequence_name text;
  function_name text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role' AND rolbypassrls) THEN
    RAISE EXCEPTION 'service_role sem BYPASSRLS: revisar configuracao antes de aplicar.';
  END IF;
  -- Lista explicita do aplicativo: nao modifica auth/storage/extensoes.
  FOREACH table_name IN ARRAY ARRAY[
    'users','marcas','modelos','categorias','materiais','pecas','peca_compatibilidade',
    'vendas','parcelas_venda','avaliacoes_fornecedor','avaliacoes_produto','wishlist',
    'mensagens','pedidos','admin_dashboard_preferences','notificacoes',
    'checklist_validacao_peca','avaliacoes_pecas','taxas_cambio'
  ] LOOP
    IF to_regclass(format('public.%I',table_name)) IS NULL THEN
      RAISE EXCEPTION 'Tabela obrigatoria ausente: %. Aplique o schema antes desta migration.',table_name;
    END IF;
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',table_name);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated',table_name);
    -- Grants por coluna sobrevivem ao REVOKE por tabela: revogar explicitamente.
    FOR column_name IN SELECT a.attname FROM pg_attribute a
      WHERE a.attrelid=to_regclass(format('public.%I',table_name)) AND a.attnum>0 AND NOT a.attisdropped
    LOOP
      EXECUTE format('REVOKE ALL (%I) ON TABLE public.%I FROM PUBLIC, anon, authenticated',column_name,table_name);
      sequence_name := pg_get_serial_sequence(format('public.%I',table_name),column_name);
      IF sequence_name IS NOT NULL THEN
        EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM PUBLIC, anon, authenticated',sequence_name);
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role',sequence_name);
      END IF;
    END LOOP;
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.%I TO service_role',table_name);
  END LOOP;
  -- Views antigas podem expor linhas mesmo quando as tabelas usam RLS.
  FOREACH table_name IN ARRAY ARRAY['fornecedor_stats','vendas_ativas','precos_publicos_moeda'] LOOP
    IF to_regclass(format('public.%I',table_name)) IS NOT NULL THEN
      EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated',table_name);
      FOR column_name IN SELECT a.attname FROM pg_attribute a
        WHERE a.attrelid=to_regclass(format('public.%I',table_name)) AND a.attnum>0 AND NOT a.attisdropped
      LOOP
        EXECUTE format('REVOKE ALL (%I) ON TABLE public.%I FROM PUBLIC, anon, authenticated',column_name,table_name);
      END LOOP;
      EXECUTE format('GRANT SELECT ON TABLE public.%I TO service_role',table_name);
    END IF;
  END LOOP;
  FOREACH function_name IN ARRAY ARRAY[
    'public.atualizar_preco_total_venda()',
    'public.decidir_avaliacao_peca(bigint,bigint,integer,jsonb,text,boolean)',
    'public.enfileirar_avaliacao_peca()',
    'public.excluir_peca_permanentemente(bigint)',
    'public.excluir_usuario_permanentemente(bigint)',
    'public.preparar_avaliacao_peca()',
    'public.proteger_historico_avaliacao()',
    'public.proteger_is_admin()',
    'public.snapshot_checklist_peca()'
  ] LOOP
    IF to_regprocedure(function_name) IS NOT NULL THEN
      EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated',function_name);
      EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role',function_name);
    END IF;
  END LOOP;
END $permissions$;
GRANT USAGE ON SCHEMA public TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.bigpecas_current_profile_id() RETURNS bigint
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $profile$
  SELECT min(p.id) FROM public.users p
  JOIN auth.users a ON lower(a.email)=lower(p.email)
  WHERE a.id=(SELECT auth.uid()) AND a.email_confirmed_at IS NOT NULL
  HAVING count(*)=1
$profile$;
-- Em caso de emails ambiguos, falhar fechado em vez de escolher outro perfil.
REVOKE ALL ON FUNCTION public.bigpecas_current_profile_id() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.bigpecas_current_profile_id() TO authenticated, service_role;
GRANT SELECT ON public.mensagens TO authenticated;
GRANT INSERT(id_remetente,id_destinatario,mensagem) ON public.mensagens TO authenticated;
DO $sequence$
DECLARE s text := pg_get_serial_sequence('public.mensagens','id');
BEGIN
  IF s IS NULL THEN RAISE EXCEPTION 'mensagens.id sem sequence/identity: revisar schema.'; END IF;
  EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated',s);
END $sequence$;

DROP POLICY IF EXISTS mensagens_participantes_select ON public.mensagens;
CREATE POLICY mensagens_participantes_select ON public.mensagens FOR SELECT TO authenticated
  USING ((SELECT public.bigpecas_current_profile_id()) IN (id_remetente,id_destinatario));
DROP POLICY IF EXISTS mensagens_participantes_restricao ON public.mensagens;
CREATE POLICY mensagens_participantes_restricao ON public.mensagens AS RESTRICTIVE FOR SELECT TO authenticated
  USING ((SELECT public.bigpecas_current_profile_id()) IN (id_remetente,id_destinatario));
DROP POLICY IF EXISTS mensagens_remetente_insert ON public.mensagens;
CREATE POLICY mensagens_remetente_insert ON public.mensagens FOR INSERT TO authenticated
  WITH CHECK (id_remetente=(SELECT public.bigpecas_current_profile_id())
    AND id_destinatario IS NOT NULL AND length(btrim(mensagem)) BETWEEN 1 AND 5000);
DROP POLICY IF EXISTS mensagens_remetente_restricao ON public.mensagens;
CREATE POLICY mensagens_remetente_restricao ON public.mensagens AS RESTRICTIVE FOR INSERT TO authenticated
  WITH CHECK (id_remetente=(SELECT public.bigpecas_current_profile_id())
    AND id_destinatario IS NOT NULL AND length(btrim(mensagem)) BETWEEN 1 AND 5000);

-- Defaults somente para objetos futuros criados como postgres.
-- Outros papeis criadores devem ser revisados separadamente.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;
NOTIFY pgrst, 'reload schema';
-- END SECURITY MIGRATION

DO $realtime$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime')
    AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime'
      AND schemaname='public' AND tablename='mensagens') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.mensagens;
  END IF;
END $realtime$;

-- Dados de referencia locais, nao exportados de producao.
INSERT INTO public.checklist_validacao_peca (nome_criterio, descricao, obrigatorio, ordem)
SELECT v.nome, v.descricao, true, v.ordem FROM (VALUES
 ('Peça real? (Futura API de validação de peça)', 'Verificação manual; API de série ainda não integrada.', 1),
 ('Imagem e/ou vídeo no anúncio?', 'Confirme que a mídia representa a peça.', 2),
 ('Possui todas as informações de tamanho e peso?', 'Comprimento, largura, altura e peso informados.', 3)
) v(nome, descricao, ordem) WHERE NOT EXISTS (SELECT 1 FROM public.checklist_validacao_peca);
INSERT INTO public.taxas_cambio(moeda, unidades_por_brl) VALUES ('BRL',1),('USD',NULL),('EUR',NULL)
ON CONFLICT (moeda) DO NOTHING;
INSERT INTO public.categorias(nome) VALUES ('Motor'),('Lataria'),('Elétrica'),('Interior'),('Suspensão'),('Freios');
INSERT INTO public.materiais(nome) VALUES ('Aço'),('Antimônio'),('Baquelite'),('Cromo'),('Alumínio'),('Borracha');
NOTIFY pgrst, 'reload schema';
COMMIT;

SELECT 'Estrutura Dev/Qas criada. Configure Auth e o backend antes de testar a aplicacao.' AS resultado;
